# ==========================================================
# IT AIN'T LUCK LLC MASTER DISCOVERY UNIVERSE
#
# Complete A-Z ticker universe monitored by the
# IAL Product Engine.
#
# bot.py imports TICKERS directly from this file.
# ==========================================================

TICKERS = [
    "AAGIY", "ABBV", "ABT", "ACAD", "ACGBY", "ACMR", "ACN", "ADBE", "ADDYY", "ADI",
    "ADP", "ADRNY", "ADSK", "ADYEY", "AFL", "AHEXY", "AI", "AIG", "AJNMY", "AKAM",
    "AKZOY", "ALAB", "ALB", "ALFVY", "ALIZY", "ALL", "ALNY", "ALSMY", "ALTR", "AMADY",
    "AMAT", "AMD", "AMGN", "AMKBY", "AMKR", "AMT", "AMZN", "ANET", "ANGPY", "ARM",
    "ARWR", "ASMPT", "ASML", "ASMVY", "ASX", "ASXFY", "ATEYY", "AUO", "AUOTY", "AVGO",
    "AXAHY", "AXP", "AXTI", "BA", "BABA", "BACHY", "BAC", "BAESY", "BAND", "BAX",
    "BAYRY", "BBSEY", "BBVA", "BDORY", "BDX", "BEAM", "BEN", "BHKLY", "BKHYY", "BIIB",
    "BITF", "BK", "BKKLY", "BKNG", "BKRKY", "BLK", "BLUE", "BMY", "BN", "BNPQY",
    "BNTGY", "BRDCY", "BRK-B", "BSX", "BTBT", "BURBY", "BVVBY", "BYDDY", "C", "CABGY",
    "CAH", "CAJPY", "CARR", "CAT", "CB", "CCEP", "CCOEY", "CDNS", "CEVA", "CFG",
    "CFRUY", "CGEMY", "CHEOY", "CHGCY", "CHKP", "CHPT", "CHTR", "CI", "CICHY", "CIFR",
    "CIHKY", "CINF", "CKHUY", "CL", "CLLNY", "CLSK", "CMA", "CMCSA", "CME", "CMI",
    "CODYY", "COF", "COHR", "COIN", "COP", "COR", "CORZ", "COST", "CRBU", "CRDO",
    "CRHKY", "CRM", "CRRFY", "CRSP", "CRWD", "CRZBY", "CSCO", "CSGS", "CSLLY", "CSUAY",
    "CSX", "CTAS", "CTTAY", "CVS", "CVX", "CYBR", "CZMWY", "DASH", "DASTY", "DBOEY",
    "DBSDY", "DDOG", "DE", "DELL", "DFS", "DHR", "DIA", "DIDIY", "DIFTY", "DIS",
    "DLAKY", "DNA", "DNBBY", "DNNGY", "DSCSY", "DSDVY", "DTEGY", "DUFRY", "DUK", "DXCM",
    "EA", "EADSY", "EBKDY", "ECL", "EDIT", "EG", "ELEZY", "ELV", "EMR", "ENLAY",
    "ENVX", "ERIE", "ESAIY", "ESLOY", "ESYJY", "ETN", "EVVTY", "EXAS", "EXEL", "EXPGY",
    "F", "FANUY", "FAST", "FATE", "FDX", "FI", "FITB", "FJTSY", "FLNC", "FMCC",
    "FNMA", "FORM", "FOX", "FOXA", "FRCOY", "FREY", "FSNUY", "FSR", "FSUGY", "FTNT",
    "FUJHY", "FUJIY", "GBOOY", "GE", "GEHC", "GEN", "GFS", "GILD", "GL", "GLNCY",
    "GM", "GMVHY", "GNRC", "GOOG", "GOOGL", "GS", "GVDNY", "GXYYY", "HACK", "HBAN",
    "HCA", "HCMLY", "HD", "HEINY", "HENKY", "HESAY", "HIG", "HIVE", "HKHHY", "HKXCY",
    "HLPPY", "HMC", "HOCPY", "HOLX", "HON", "HOOD", "HPE", "HPQ", "HSQVY", "HUM",
    "HUT", "HWM", "HXGBY", "IBM", "IBDRY", "ICE", "IDEXY", "IDXX", "IFNNY", "IHICY",
    "ILMN", "IMBBY", "IMPUY", "INDO", "INTC", "INTU", "IONS", "IR", "IREN", "ISNPY",
    "ISRG", "IWM", "JAPSY", "JBAXY", "JCI", "JMHLY", "JMPLY", "JNJ", "JPM", "JSAIY",
    "KBCSY", "KCDMY", "KEY", "KHC", "KHNGY", "KKPNY", "KLAC", "KMTUY", "KNRRY", "KO",
    "KPCPY", "KRYAY", "KYOAY", "LAC", "LCID", "LGGNY", "LGRDY", "LHX", "LI", "LIN",
    "LKNCY", "LLY", "LMT", "LNC", "LNNGY", "LNVGY", "LOW", "LRLCY", "LSCC", "LSRCY",
    "LTGHY", "LRCX", "LVMUY", "LYV", "LZAGY", "MA", "MAKSY", "MARA", "MARUY", "MBGYY",
    "MCD", "MCHP", "MDT", "MET", "META", "MGDDY", "MHGVY", "MIELY", "MITEY", "MITSY",
    "MKKGY", "MKTX", "MMM", "MO", "MPNGY", "MPWR", "MRAAY", "MRK", "MRNA", "MRVL",
    "MS", "MSADY", "MSFT", "MTB", "MTCH", "MTNOY", "MTSFY", "MTSI", "MTUAY", "MU",
    "MZDAY", "NABZY", "NCBDY", "NDBKY", "NDSN", "NEE", "NET", "NEXOY", "NFLX", "NGLOY",
    "NHYDY", "NINOY", "NIO", "NKE", "NLST", "NNGRY", "NOC", "NOW", "NPSCY", "NPSNY",
    "NRDBY", "NSANY", "NSRGY", "NTDOY", "NTLA", "NTOIY", "NTTYY", "NVDA", "NVZMY", "NXPI",
    "OKTA", "OMRNY", "ON", "ORCL", "ORKLY", "OTGLY", "OTIS", "OTSKY", "PANW", "PARA",
    "PCAR", "PFE", "PG", "PGR", "PH", "PINS", "PLAB", "PLD", "PLL", "PLTR",
    "PM", "PNC", "PNGAY", "PPERY", "PPRUY", "PRNDY", "PROSY", "PRU", "PRYMY", "PSX",
    "PTAIY", "PUBGY", "PWR", "PYPL", "QABSY", "QCOM", "QQQ", "QS", "RACE", "RANJY",
    "RBGLY", "RBLX", "RDEIY", "REGN", "REPYY", "RF", "RGA", "RIOT", "RIVN", "RMBS",
    "RMD", "RMVEY", "RNECY", "RNG", "RNMBY", "ROK", "ROKU", "RTX", "RWEOY", "RXRX",
    "RYCEY", "S", "SAFRY", "SAIC", "SALRY", "SANA", "SAP", "SAUHY", "SAXPY", "SBGSY",
    "SBUX", "SCGLY", "SCHW", "SCMWY", "SDVKY", "SDXAY", "SEKEY", "SEOAY", "SFTBY", "SGAPY",
    "SGIOY", "SGPYY", "SGSOY", "SHECY", "SHOP", "SIEGY", "SIMO", "SINGY", "SITM", "SKBSY",
    "SKFRY", "SLDP", "SLLDY", "SMERY", "SMGZY", "SMH", "SMMNY", "SMMYY", "SMNNY", "SMPNY",
    "SMTC", "SMTOY", "SNAP", "SNMRY", "SNOW", "SO", "SOFI", "SOUHY", "SOUN", "SOXX",
    "SPGI", "SPKKY", "SPLK", "SPOT", "SPSC", "SPY", "SRE", "SRPT", "SSDOY", "SSEZY",
    "SSMXY", "SSUMY", "STE", "STLA", "STM", "STRNY", "STT", "SUHJY", "SVNDY", "SVNLY",
    "SWDBY", "SWGAY", "SWKS", "SWRAY", "SYF", "SYIEY", "SYK", "SXYAY", "T", "TCEHY",
    "TEAM", "TENB", "TER", "TEZNY", "TFC", "TGT", "TGOPY", "TKAMY", "TKOMY", "TLPFY",
    "TLSNY", "TLT", "TM", "TMO", "TMUS", "TMVWY", "TOELY", "TRUMY", "TRYIY", "TSLA",
    "TSM", "TT", "TTDKY", "TTNDY", "TTWO", "TWST", "TXN", "TXT", "UBER", "UBSFY",
    "UCBJY", "UMC", "UNCRY", "UNH", "UNM", "UNP", "UPMMY", "UPS", "URI", "USB",
    "UVXY", "V", "VCISY", "VDMCY", "VECO", "VEOEY", "VERV", "VIVHY", "VIXY", "VLEEY",
    "VLO", "VLVLY", "VOO", "VRSN", "VRNS", "VRT", "VRTX", "VWAGY", "VWDRY", "VZ",
    "WBD", "WDC", "WEGRY", "WEGZY", "WFAFY", "WFC", "WKHS", "WM", "WMMVY", "WMT",
    "WRB", "WTBDY", "WULF", "XIACY", "XLE", "XLF", "XLI", "XLK", "XLP", "XLRE",
    "XLU", "XLV", "XLY", "XME", "XNGSY", "XOM", "XPEV", "XYL", "YAHOY", "YARIY",
    "YASKY", "ZBH", "ZLNDY", "ZM", "ZS", "ZTS", "ZURVY",
]
